"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var parser_1 = require("./parser");
var printer_1 = require("./printer");
var rules_1 = require("./rules");
var printers_1 = require("./printers");
exports.defaultParser = parser_1.newParser(rules_1.defaultRules);
exports.defaultHTMLPrinter = printer_1.newPrinter(printers_1.html);
var parser_2 = require("./parser");
exports.newParser = parser_2.newParser;
var printers_2 = require("./printers");
exports.newHTMLPrinters = printers_2.newHTMLPrinters;
var rules_2 = require("./rules");
exports.defaultRules = rules_2.defaultRules;
